export const STOCK_LIST = [
  { symbol: 'AAPL', name: 'Apple Inc.' },
  { symbol: 'MSFT', name: 'Microsoft Corporation' },
  { symbol: 'GOOGL', name: 'Alphabet Inc.' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation' },
  { symbol: 'META', name: 'Meta Platforms, Inc.' },
  { symbol: 'TSLA', name: 'Tesla, Inc.' },
  { symbol: 'BRK-B', name: 'Berkshire Hathaway Inc.' },
  { symbol: 'UNH', name: 'UnitedHealth Group Incorporated' },
  { symbol: 'JNJ', name: 'Johnson & Johnson' },
  { symbol: 'V', name: 'Visa Inc.' },
  { symbol: 'XOM', name: 'Exxon Mobil Corporation' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.' },
  { symbol: 'WMT', name: 'Walmart Inc.' },
  { symbol: 'PG', name: 'The Procter & Gamble Company' },
  { symbol: 'MA', name: 'Mastercard Incorporated' },
  { symbol: 'HD', name: 'The Home Depot, Inc.' },
  { symbol: 'CVX', name: 'Chevron Corporation' },
  { symbol: 'LLY', name: 'Eli Lilly and Company' },
  { symbol: 'ABBV', name: 'AbbVie Inc.' },
  { symbol: 'MRK', name: 'Merck & Co., Inc.' },
  { symbol: 'KO', name: 'The Coca-Cola Company' },
  { symbol: 'PEP', name: 'PepsiCo, Inc.' },
  { symbol: 'BAC', name: 'Bank of America Corporation' },
  { symbol: 'AVGO', name: 'Broadcom Inc.' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific Inc.' },
  { symbol: 'COST', name: 'Costco Wholesale Corporation' },
  { symbol: 'MCD', name: 'McDonald\'s Corporation' },
  { symbol: 'CSCO', name: 'Cisco Systems, Inc.' },
  { symbol: 'ABT', name: 'Abbott Laboratories' },
  { symbol: 'DHR', name: 'Danaher Corporation' },
  { symbol: 'ACN', name: 'Accenture plc' },
  { symbol: 'LIN', name: 'Linde plc' },
  { symbol: 'DIS', name: 'The Walt Disney Company' },
  { symbol: 'NKE', name: 'NIKE, Inc.' },
  { symbol: 'PFE', name: 'Pfizer Inc.' },
  { symbol: 'ADBE', name: 'Adobe Inc.' },
  { symbol: 'CRM', name: 'Salesforce, Inc.' },
  { symbol: 'TXN', name: 'Texas Instruments Incorporated' },
  { symbol: 'CMCSA', name: 'Comcast Corporation' },
  { symbol: 'VZ', name: 'Verizon Communications Inc.' },
  { symbol: 'NFLX', name: 'Netflix, Inc.' },
  { symbol: 'WFC', name: 'Wells Fargo & Company' },
  { symbol: 'UPS', name: 'United Parcel Service, Inc.' },
  { symbol: 'PM', name: 'Philip Morris International Inc.' },
  { symbol: 'AMD', name: 'Advanced Micro Devices, Inc.' },
  { symbol: 'INTC', name: 'Intel Corporation' },
  { symbol: 'QCOM', name: 'QUALCOMM Incorporated' },
  { symbol: 'RTX', name: 'Raytheon Technologies Corporation' },
  { symbol: 'HON', name: 'Honeywell International Inc.' },
  { symbol: 'UNP', name: 'Union Pacific Corporation' },
  { symbol: 'BA', name: 'The Boeing Company' },
  { symbol: 'IBM', name: 'International Business Machines Corporation' },
  { symbol: 'GE', name: 'General Electric Company' },
  { symbol: 'CAT', name: 'Caterpillar Inc.' },
  { symbol: 'MDT', name: 'Medtronic plc' },
  { symbol: 'AMGN', name: 'Amgen Inc.' },
  { symbol: 'SBUX', name: 'Starbucks Corporation' },
  { symbol: 'GS', name: 'The Goldman Sachs Group, Inc.' },
  { symbol: 'MS', name: 'Morgan Stanley' },
  { symbol: 'BLK', name: 'BlackRock, Inc.' },
  { symbol: 'C', name: 'Citigroup Inc.' },
  { symbol: 'LMT', name: 'Lockheed Martin Corporation' },
  { symbol: 'DE', name: 'Deere & Company' },
  { symbol: 'MMM', name: '3M Company' },
  { symbol: 'F', name: 'Ford Motor Company' },
  { symbol: 'GM', name: 'General Motors Company' },
  { symbol: 'T', name: 'AT&T Inc.' },
  { symbol: 'TMUS', name: 'T-Mobile US, Inc.' },
  { symbol: 'CVS', name: 'CVS Health Corporation' },
  { symbol: 'TGT', name: 'Target Corporation' },
  { symbol: 'SPY', name: 'SPDR S&P 500 ETF Trust' },
  { symbol: 'QQQ', name: 'Invesco QQQ Trust' },
  { symbol: 'IWM', name: 'iShares Russell 2000 ETF' },
  { symbol: 'BTC-USD', name: 'Bitcoin USD' },
  { symbol: 'ETH-USD', name: 'Ethereum USD' }
];
